name: 'Pale Moon Addon Action'
description: 'Upload your addon to Pale Moon'
branding:
  icon: 'play'
  color: 'blue'
author: 'rafaelgssa'
inputs:
  slug:
    description: 'Your addons slug as defined by Pale Moon'
  xpi:
    description: 'Path to your addons .xpi file'
  username:
    description: 'Your username on addons.palemoon.org'
  password:
    description: 'Your password on addons.palemoon.org'
runs:
  using: 'node12'
  main: 'lib/main.js'
